#:kivy 1.0.9
<KhanFrame>:
    Label:
        font_size: 20
        text: 'CAN Frame'


<KhanLogger>:
    GridLayout:
        cols: 2
        padding: 10
        spacing: 10
        size: root.width, root.height
        BoxLayout:
            orientation: 'vertical'
            size_hint: 0.25, 1
            Button: 
                text: 'Start Serial'
                font_size: 20
                on_press: root.start_serial()

                
            Button: 
                text: 'End Serial'
                font_size: 20
                on_press: root.stop_serial()

            Button: 
                text: 'Clear Log'
                font_size: 20
                on_press: root.clear_log()

        BoxLayout:
            size_hint: 0.75, 1
            id: can_list
            orientation: 'vertical'
        
        

            